# Site settings
title: No Fixed Plans
email: griffin@nofixedplans.xyz
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://nofixedplans.xyz"

twitter_username: gcaprio
github_username: gcaprio

# Build settings
markdown: kramdown
